# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "79ddd7f869ebec952bd74a866243a287"
application_url = "https://absolutely-reductions-approximately-fx.trycloudflare.com"
embedded = true
name = "Firstapp"
handle = "firstapp-564"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://absolutely-reductions-approximately-fx.trycloudflare.com/auth/callback",
  "https://absolutely-reductions-approximately-fx.trycloudflare.com/auth/shopify/callback",
  "https://absolutely-reductions-approximately-fx.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "haos-milk.myshopify.com"
automatically_update_urls_on_dev = true
